CREATE DATABASE IF NOT EXISTS user_service;
CREATE DATABASE IF NOT EXISTS booking_service;
CREATE DATABASE IF NOT EXISTS booking_system;

USE user_service;
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

USE booking_service;
CREATE TABLE IF NOT EXISTS bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  roomId INT NOT NULL,
  checkIn VARCHAR(10) NOT NULL,
  checkOut VARCHAR(10) NOT NULL,
  totalPrice DECIMAL(12,2) NOT NULL,
  status VARCHAR(50) DEFAULT 'pending',
  userId INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
